---
# tasks file for frontend

- name: Run Frontend container
  community.docker.docker_container:
    name: frontend
    image: quentindhr/devops-frontend:latest
    state: started
    restart_policy: always
    networks:
      - name: app-network
  vars:
    ansible_python_interpreter: /usr/bin/python3
