services:
  database:
    build: ./Java/db
    container_name: database
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./Java
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    networks:
      - app-network
    depends_on:
      - database
    restart: always

  httpd:
    build: ./httpd
    container_name: httpd
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local