FROM httpd:2.4-alpine

COPY index.html /usr/local/apache2/htdocs/
COPY httpd.conf /usr/local/apache2/conf/httpd.conf
# Force rebuild Lun 27 oct 2025 16:57:40 CET
# Rebuild Mar 28 oct 2025 09:52:51 CET
