name: Check Frontend

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.ANSIBLE_HOST }} >> ~/.ssh/known_hosts
      
      - name: Check if frontend container is running
        run: |
          ssh -i ~/.ssh/id_rsa admin@${{ secrets.ANSIBLE_HOST }} "docker ps | grep frontend"
      
      - name: Check frontend logs
        run: |
          ssh -i ~/.ssh/id_rsa admin@${{ secrets.ANSIBLE_HOST }} "docker logs frontend --tail 50"
      
      - name: Test frontend from inside server
        run: |
          ssh -i ~/.ssh/id_rsa admin@${{ secrets.ANSIBLE_HOST }} "curl -s http://frontend:80/ | head -30"
      
      - name: Test from httpd to frontend
        run: |
          ssh -i ~/.ssh/id_rsa admin@${{ secrets.ANSIBLE_HOST }} "docker exec httpd curl -s http://frontend:80/ | head -30"
