spring:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://database:5432/mydatabase
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
